### ISSUE TITLE
restart on cert-change

### ISSUE THREAD

**Issue by joker234** [cherti/authguard#2]
If you use automatically updating certificate systems like letsencrypt, you have issues that the certificate will be outdated, because you have to restart authguard for getting the new certificates. Is it easily possible to let authguard watch cert-changes and reload the cert in runtime?

Do you have another fix solution to combine authguard with letsencrypt?

**Comment by cherti** [comment]
I would not do a automated restart. That would not only include code for a watchdog, but also code to test if the new certificates are valid certificates before using them (or one could crash otherwise, not too beautiful).

I'd like to keep code like that out of authguard to keep the code compact.

Regarding letsencrypt, I'd propose to simply include a restart of affected authguards into your letsencrypt-script/-cronjob/.timer/-whateverfloatsyourboat.
